ALTER TABLE pedidos_pipa ADD COLUMN IF NOT EXISTS pipa_latitud DOUBLE PRECISION
  CHECK (pipa_latitud BETWEEN -90 AND 90);
ALTER TABLE pedidos_pipa ADD COLUMN IF NOT EXISTS pipa_longitud DOUBLE PRECISION
  CHECK (pipa_longitud BETWEEN -180 AND 180);
ALTER TABLE pedidos_pipa ADD COLUMN IF NOT EXISTS pipa_precision DOUBLE PRECISION
  CHECK (pipa_precision BETWEEN 0 AND 10000);
ALTER TABLE pedidos_pipa ADD COLUMN IF NOT EXISTS pipa_observada_en TIMESTAMPTZ;
ALTER TABLE pedidos_pipa ADD COLUMN IF NOT EXISTS pipa_recibida_en TIMESTAMPTZ;
